### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ManuelQ59** [rlyonheart/centaur.04#1]
and if I want to search through a .txt text file, how do I do?

**Comment by ManuelQ59** [comment]
> and if I want to search through a .txt text file, how do I do?

I have a certain number of websites to analyze, how do I do, help me?

**Comment by rlyonheart** [comment]
Hey, sorry i haven't added that feature yet but, i'll consider working on it.

**Comment by ManuelQ59** [comment]
> Oye, lo siento, no he agregado esa función todavía, pero consideraré trabajar en ella.

Okey Thanks
